### ISSUE TITLE
TypeError on app start

### ISSUE THREAD

**Issue by trns1997** [pkcwong/conjur#13]
```
yarn run v1.22.5
$ concurrently --kill-others-on-fail "yarn run start:client" "yarn run start:server"
$ yarn --cwd server start
$ yarn --cwd client start
$ babel-node -- ./index.js
$ react-scripts start
[1] Server listening at port 8080.
[0] [HPM] Proxy created: /api  -> http://localhost:8080/
[0] ℹ ｢wds｣: Project is running at http://192.168.1.44/
[0] ℹ ｢wds｣: webpack output is served from /
[0] ℹ ｢wds｣: Content not from webpack is served from /home/thomas/poseApp/client/public
[0] ℹ ｢wds｣: 404s will fallback to /index.html
[0] Starting the development server...
[0] 
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[0]     at validateString (internal/validators.js:120:11)
[0]     at Object.join (path.js:1039:7)
[0]     at noopServiceWorkerMiddleware (/home/thomas/poseApp/client/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/home/thomas/poseApp/client/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:317:13)
[0]     at /home/thomas/poseApp/client/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/home/thomas/poseApp/client/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/home/thomas/poseApp/client/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:317:13)
[0]     at /home/thomas/poseApp/client/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:275:10)
[0]     at handleWebpackInternalMiddleware (/home/thomas/poseApp/client/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
[0]     at Layer.handle [as handle_request] (/home/thomas/poseApp/client/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[0]     at validateString (internal/validators.js:120:11)
[0]     at Object.join (path.js:1039:7)
[0]     at noopServiceWorkerMiddleware (/home/thomas/poseApp/client/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/home/thomas/poseApp/client/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:317:13)
[0]     at /home/thomas/poseApp/client/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/home/thomas/poseApp/client/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/home/thomas/poseApp/client/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:317:13)
[0]     at /home/thomas/poseApp/client/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/home/thomas/poseApp/client/node_modules/express/lib/router/index.js:275:10)
[0]     at handleWebpackInternalMiddleware (/home/thomas/poseApp/client/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
[0]     at Layer.handle [as handle_request] (/home/thomas/poseApp/client/node_modules/express/lib/router/layer.js:95:5)
[0] Compiled successfully!
[0] 
[0] You can now view conjure in the browser.
[0] 
[0]   Local:            http://localhost:3000/
[0]   On Your Network:  http://192.168.1.44:3000/
[0] 
[0] Note that the development build is not optimized.
[0] To create a production build, use yarn build.
```
The following error occurs when I use the template, but upgrading the `react-scripts` version in the `client/package.json` seems to solve the issue. 

My Upgrade in `client/package.json`:
`"react-scripts": "3.3.0"` to `"react-scripts": "^3.4.1"`

**Comment by pkcwong** [comment]
@trns1997 
Issue verified, thanks for the fix instructions. You can go ahead and raise a PR, or I can do it as well.
